### ISSUE TITLE
When not verifying emoji, random "n" will pop up.

### ISSUE THREAD

**Issue by hard-shutdown** [NovaOSS/nova-web#1]
ok uh so this is hard to describe

if you use a valid terms URL (e.x. `https://nova-oss.com/legal/terms?verify=mwsCVLpy`) then the emoji will popup

if the `verify` param is invalid or not supplied (e.x. `https://nova-oss.com/legal/terms?verify=LOLOLOL` or `https://nova-oss.com/legal/terms`) then a random "n" will show up

so yeah :)

**Comment by RayBytes** [comment]
@nsde

**Comment by nsde** [comment]
I'll look into it :)

**Comment by nsde** [comment]
Fixed in https://github.com/NovaOSS/nova-web/commit/e2d29c844a4d63ef1d8fa8535fa13416d73cf6d0
